# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "mc275"
repo_name: "arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 100
paper_early_days: 365

publish_readme: True
publish_gitpage: False
publish_wechat: False

# file paths
json_readme_path: "./docs/arxiv-daily.json"
json_gitpage_path: "./docs/daily-web.json"
json_wechat_path: "./docs/daily-wechat.json"

md_readme_path: "README.md"
md_gitpage_path: "./docs/index.md"
md_wechat_path: "./docs/wechat.md"

# keywords to search
keywords:
  "3DGS":
    filters: ["Gaussian Splatting"]
  "SLAM":
    filters: ["SLAM", "Visual Odometry"]
  "SFM":
    filters: ["SFM", "Structure from Motion"]
  "Visual Localization":
    filters:
      [
        "Visual Localization",
        "Camera Localization",
        "Camera Re-localisation",
        "Loop Closure Detection",
        "visual place recognition",
        "image retrieval",
      ]
  "Keypoint Detection":
    filters: ["Keypoint Detection", "Feature Descriptor"]
  "Image Matching":
    filters:
      [
        "Image Matching",
        "Keypoint Matching",
        "Line Segment Detection",
        "Local Feature Matching",
      ]
